### ISSUE TITLE
RFC: HLSA for CSS variables

### ISSUE THREAD

**Issue by McManning** [osuresearch/ui#34]
I *love* the way GraphiQL uses hlsa as the standard for their CSS variables - this lets them blend colors and control alpha a lot more easily, and possibly do some automatic-contrasting. 

E.g.:

```css
body:not(.graphql-light) .graphiql-container {
  --color-primary: 338, 100%, 67%;
  --color-secondary: 243, 100%, 77%;
}

.cm-s-graphiql {
  color: hsla(var(--color-neutral),var(--alpha-tertiary));
}
```

Think about whether or not we can benefit from a design choice like this earlier on. I think it'd honestly make it easier to generate secondary palette colors for sure.
